[package]
name = "opencv_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.68.0"
zmq_remote_api = { path = "../../" }
